### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by wujunbin** [dancannon/better-go-playground#1]
better go playground  cannot autocomplete. ?  why ? i have installed the extension.

**Comment by dancannon** [comment]
You need to press ctrl+space to activate the autocompletion. Could you give this a try and let me know if that answers your question.

**Comment by wujunbin** [comment]
Does is just support keyword completion?   i do not find code completion.  eg: fmt.Printf() ...

**Comment by dancannon** [comment]
Unfortunately not at this time.

**Comment by avinassh** [comment]
I am using Chrome (v59) and latest plugin from Chrome Webstore on my OS X machine. How do I activate auto complete?
