### ISSUE TITLE
Firefox Webextension

### ISSUE THREAD

**Issue by fenimore** [dancannon/better-go-playground#3]
I don't know if this is something you're considering, but this would be nice to have for Firefox (for, ehem, the rest of us 😸 ). From what I understand Firefox WebExtension API should allow for a kinda one to one porting of addons like this, and in my experience it's mostly true. So I tried to do  this with your addon, but I failed, mostly because I don't know how `bower` works. Maybe you could give it a shot?

Anyway, I don't know if you're considering this, but I thought I'd put it out there.

**Comment by dancannon** [comment]
Sorry but I have decided to de-list the extension and will not be looking into any firefox extensions.
